//
// Created by theuszero on 10/19/20.
//

#ifndef SISTEMAS_OPERATIVOS_TAREAS_ALLFUNCTIONS_H
#define SISTEMAS_OPERATIVOS_TAREAS_ALLFUNCTIONS_H

int validation(char *number);

#endif //SISTEMAS_OPERATIVOS_TAREAS_ALLFUNCTIONS_H
